BAD_WORDS = {
    "ahmoq", "axmoq",
    "am", "amcha", "ambaliq", "aminga",
    "bitch", "bich",
    "blyat", "blet", "ble",
    "boq", "boqkalla",
    "buvini ami",
    "chochoq", "cho'choq",
    "dalban", "dalbayob", "dalbayop",
    "daun",
    "fuck", "fuck you", "fucking", "fuck off",
    "foxisha",
    "gandon", "garang",
    "gay", "gey",
    "gnida",
    "haromi", "xaromi",
    "hunasa",
    "iflos", "iplos",
    "idi naxuy",
    "it", "itbet",
    "jala", "jalab", "jalap", "jallab", "jallap", "jalla",
    "jinni",
    "kispurush",
    "kot", "ko't", "qotoq", "qotoqbosh", "qotaq",
    "lox",
    "mol",
    "nedagon",
    "nigger", "nigga",
    "om",
    "onangni", "onangni sikay", "onangni ami",
    "pizda", "pizdes", "p1zdes",
    "pidaras", "pidaraz", "pidr",
    "pashol na xuy",
    "qanjiq", "qanchiq", "qanciq",
    "seks", "sex", "sexy", "seksi",
    "sik", "sikay", "sikish", "siktim", "ske",
    "skay", "skey",
    "suchka", "suka", "sukka",
    "tashoq", "tashshoq",
    "tupoy",
    "tvar",
    "wtf",
    "xuy", "xuyeplet", "xuyesos",
    "yeban", "yebat", "yeblan", "yebnu",
    "yiban", "yibanat",
    "zaybal",
}
